# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=26.2
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
# Mod Properties
mod_version=0.3.6
maven_group=com.glisco
archives_base_name=deathlog
# Dependencies
fabric_api_version=0.152.1+26.2

# https://github.com/emilyploszaj/trinkets/releases
trinkets_version=3.10.0

# https://maven.ladysnake.org/#/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-api/cardinal-components-base
cca_version=7.1.0-beta.1

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=20.0.0-beta.3

# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.13.0+26.1

# https://github.com/NucleoidMC/Server-Translations/releases
server_translations_version=3.1.0+26.2

# https://github.com/Patbox/sgui
sgui_version=2.1.0+26.2

permission_api_version=0.7.0